### ISSUE TITLE
Set up GCP App Engine

### ISSUE THREAD

**Issue by lshlyapnikov** [lshlyapnikov/prm.js#16]
Free tier:
- https://cloud.google.com/free/docs/gcp-free-tier
- https://cloud.google.com/appengine/docs/standard/python3/config/appref#automatic_scaling

app.yaml setting:
    ```
    runtime: nodejs10
    instance_class: F1
    automatic_scaling:
        min_instances: 0
        max_instances: 1
        max_concurrent_requests: 50
    ```
